[package]
name = "cosmic-toggle-terminal"
version = "0.2.0"
edition = "2024"
license = "GPL-3.0-only"
authors = ["Alan Chen <argot@digikata.com>"]
description = "Command line utility to map a cosmic hotkey to to open/close a popup terminal"

[dependencies]
wayland-backend = "0.3"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", features = ["client"] }
